"""Bootstrap uncertainty for calibrated Gaussian observation parameters.

This script regenerates the seed-999 calibration rollouts, bootstraps the
in-window feature rows within each courtesy class, and writes a compact LaTeX
table for the paper.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path
from typing import Dict, List

import numpy as np

from calibrate_observation_model import (
    ACTIVE_FEATURES,
    COURTESY_TYPES,
    _MIN_SIGMA,
    _collect_features,
    _validate_model,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--episodes", type=int, default=60)
    parser.add_argument("--seed", type=int, default=999)
    parser.add_argument("--traffic-density", type=float, default=1.0)
    parser.add_argument("--bootstraps", type=int, default=2000)
    parser.add_argument("--output-dir", default="observation_uncertainty_analysis")
    parser.add_argument("--table", default="paper/tables/table_observation_bootstrap_uncertainty.tex")
    return parser.parse_args()


def fit(values: np.ndarray, min_sigma: float) -> tuple[float, float]:
    values = values[np.isfinite(values)]
    if len(values) < 2:
        return (float(np.nanmean(values)) if len(values) else 0.0, min_sigma)
    return float(np.mean(values)), max(float(np.std(values, ddof=1)), min_sigma)


def ci(values: np.ndarray) -> tuple[float, float]:
    return float(np.percentile(values, 2.5)), float(np.percentile(values, 97.5))


def fmt_interval(point: float, low: float, high: float, digits: int = 2) -> str:
    return f"{point:.{digits}f} [{low:.{digits}f}, {high:.{digits}f}]"


def collect_rows(args: argparse.Namespace) -> Dict[str, List[dict]]:
    rows_by_mode: Dict[str, List[dict]] = {}
    for courtesy in COURTESY_TYPES:
        feats = _collect_features(courtesy, args.episodes, args.seed, args.traffic_density)
        rows_by_mode[courtesy] = feats["_rows"]
    return rows_by_mode


def bootstrap(rows_by_mode: Dict[str, List[dict]], n_boot: int, seed: int) -> tuple[dict, np.ndarray]:
    rng = np.random.default_rng(seed)
    arrays = {
        mode: {
            feat: np.array([row[feat] for row in rows if math.isfinite(row[feat])], dtype=float)
            for feat in ACTIVE_FEATURES
        }
        for mode, rows in rows_by_mode.items()
    }

    point_model = {}
    for mode in COURTESY_TYPES:
        point_model[mode] = {}
        for feat in ACTIVE_FEATURES:
            mu, sigma = fit(arrays[mode][feat], _MIN_SIGMA[feat])
            point_model[mode][f"{feat}_mu"] = mu
            point_model[mode][f"{feat}_sigma"] = sigma

    samples = {
        mode: {feat: {"mu": [], "sigma": []} for feat in ACTIVE_FEATURES}
        for mode in COURTESY_TYPES
    }
    accuracies = []
    original_rows = [row for rows in rows_by_mode.values() for row in rows]

    for _ in range(n_boot):
        model = {}
        for mode in COURTESY_TYPES:
            model[mode] = {}
            for feat in ACTIVE_FEATURES:
                vals = arrays[mode][feat]
                resampled = rng.choice(vals, size=len(vals), replace=True)
                mu, sigma = fit(resampled, _MIN_SIGMA[feat])
                samples[mode][feat]["mu"].append(mu)
                samples[mode][feat]["sigma"].append(sigma)
                model[mode][f"{feat}_mu"] = mu
                model[mode][f"{feat}_sigma"] = sigma
        accuracies.append(_validate_model(model, original_rows)["binary_belief_accuracy"])

    return {"point_model": point_model, "samples": samples}, np.array(accuracies)


def write_table(payload: dict, accuracies: np.ndarray, table_path: Path) -> None:
    point_model = payload["point_model"]
    samples = payload["samples"]
    rows = []
    names = {
        "ard": "Abs. rel. distance",
        "mvs": "Merge speed",
        "mva": "Merge accel.",
    }
    for feat in ACTIVE_FEATURES:
        coop_mu_ci = ci(np.array(samples["cooperative"][feat]["mu"]))
        coop_sigma_ci = ci(np.array(samples["cooperative"][feat]["sigma"]))
        nc_mu_ci = ci(np.array(samples["non_cooperative"][feat]["mu"]))
        nc_sigma_ci = ci(np.array(samples["non_cooperative"][feat]["sigma"]))
        rows.append(
            f"{names[feat]} & "
            f"{fmt_interval(point_model['cooperative'][f'{feat}_mu'], *coop_mu_ci)} & "
            f"{fmt_interval(point_model['cooperative'][f'{feat}_sigma'], *coop_sigma_ci)} & "
            f"{fmt_interval(point_model['non_cooperative'][f'{feat}_mu'], *nc_mu_ci)} & "
            f"{fmt_interval(point_model['non_cooperative'][f'{feat}_sigma'], *nc_sigma_ci)} \\\\"
        )
    acc_low, acc_high = ci(accuracies)
    acc_point = float(np.mean(accuracies))
    tex = "\n".join([
        "% Auto-generated by analyze_observation_uncertainty.py",
        "\\begin{table}[htbp]",
        "\\centering",
        "\\caption{Bootstrap uncertainty for calibrated observation parameters. "
        "Entries show point estimate [2.5\\%, 97.5\\%] from bootstrap resampling "
        "within each courtesy class.}",
        "\\label{tab:obs_bootstrap_uncertainty}",
        "\\small",
        "\\resizebox{\\textwidth}{!}{%",
        "\\begin{tabular}{lcccc}",
        "\\toprule",
        "\\textbf{Feature} & \\textbf{Coop. $\\mu$} & \\textbf{Coop. $\\sigma$} & "
        "\\textbf{Non-coop. $\\mu$} & \\textbf{Non-coop. $\\sigma$} \\\\",
        "\\midrule",
        *rows,
        "\\bottomrule",
        "\\end{tabular}}",
        "\\begin{tablenotes}",
        "\\small",
        f"\\item Bootstrap-induced classification accuracy variation is "
        f"{100.0 * acc_point:.1f}\\% [{100.0 * acc_low:.1f}\\%, {100.0 * acc_high:.1f}\\%]. "
        "The non-cooperative acceleration variance is floor-limited by "
        "$\\sigma_\\text{min}{=}0.5$.",
        "\\end{tablenotes}",
        "\\end{table}",
    ])
    table_path.parent.mkdir(parents=True, exist_ok=True)
    table_path.write_text(tex + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    rows_by_mode = collect_rows(args)
    payload, accuracies = bootstrap(rows_by_mode, args.bootstraps, args.seed + 2026)
    write_table(payload, accuracies, Path(args.table))


if __name__ == "__main__":
    main()
