"""Generate LaTeX tables for Tier-1 robustness experiments when outputs exist."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd


def pct(x: float) -> str:
    return f"{100.0 * float(x):.1f}\\%"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--confirmatory-dir", default="eval_confirmatory_1960")
    parser.add_argument("--fullcov-dir", default="eval_fullcov_300")
    parser.add_argument("--noise-dir", default="noise_stress_sweep")
    parser.add_argument("--bias-dir", default="generating_policy_bias_analysis")
    parser.add_argument("--output-dir", default="paper/tables")
    return parser.parse_args()


def write_confirmatory_table(run_dir: Path, out_dir: Path) -> None:
    summary_path = run_dir / "policy_summary.csv"
    if not summary_path.exists():
        return
    df = pd.read_csv(summary_path)
    order = {
        "pomcp_policy": 0,
        "oracle_policy": 1,
        "belief_policy": 2,
        "rule_policy": 3,
        "random_policy": 4,
    }
    rows = []
    for _, row in df.sort_values("policy_name", key=lambda s: s.map(order).fillna(99)).iterrows():
        rows.append(
            f"{row['policy_name'].replace('_', '\\_')} & {int(row['episodes'])} & "
            f"{pct(row['collision_rate'])} & {float(row['mean_reward']):.2f} & "
            f"{pct(row['close_call_rate'])} \\\\"
        )
    tex = "\n".join([
        "% Auto-generated by make_tier1_tables.py",
        "\\begin{table}[htbp]",
        "\\centering",
        "\\caption{Confirmatory matched evaluation for heuristic policies at "
        "$n{=}1{,}960$ episodes per policy.}",
        "\\label{tab:confirmatory_1960}",
        "\\small",
        "\\begin{tabular}{lcccc}",
        "\\toprule",
        "\\textbf{Policy} & \\textbf{$n$} & \\textbf{Collision} & "
        "\\textbf{Reward} & \\textbf{Close-call} \\\\",
        "\\midrule",
        *rows,
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ])
    (out_dir / "table_confirmatory_1960.tex").write_text(tex + "\n", encoding="utf-8")


def write_fullcov_table(run_dir: Path, out_dir: Path) -> None:
    summary_path = run_dir / "policy_summary.csv"
    if not summary_path.exists():
        return
    df = pd.read_csv(summary_path)
    rows = []
    for _, row in df.sort_values("policy_name").iterrows():
        rows.append(
            f"{row['policy_name'].replace('_', '\\_')} & {pct(row['collision_rate'])} & "
            f"{float(row['mean_reward']):.2f} & {pct(row['close_call_rate'])} \\\\"
        )
    tex = "\n".join([
        "% Auto-generated by make_tier1_tables.py",
        "\\begin{table}[htbp]",
        "\\centering",
        "\\caption{Closed-loop evaluation with the full-covariance observation likelihood.}",
        "\\label{tab:fullcov_closed_loop}",
        "\\small",
        "\\begin{tabular}{lccc}",
        "\\toprule",
        "\\textbf{Policy} & \\textbf{Collision} & \\textbf{Reward} & \\textbf{Close-call} \\\\",
        "\\midrule",
        *rows,
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ])
    (out_dir / "table_fullcov_closed_loop.tex").write_text(tex + "\n", encoding="utf-8")


def write_noise_table(run_dir: Path, out_dir: Path) -> None:
    summary_path = run_dir / "noise_stress_summary.csv"
    if not summary_path.exists():
        return
    df = pd.read_csv(summary_path)
    rows = []
    for _, row in df.sort_values(["noise_scale", "policy_name"]).iterrows():
        rows.append(
            f"{float(row['noise_scale']):.2f} & {row['policy_name'].replace('_', '\\_')} & "
            f"{pct(row['collision_rate'])} & {float(row['mean_reward']):.2f} \\\\"
        )
    tex = "\n".join([
        "% Auto-generated by make_tier1_tables.py",
        "\\begin{table}[htbp]",
        "\\centering",
        "\\caption{Observation-noise stress test under matched episodes.}",
        "\\label{tab:noise_stress}",
        "\\small",
        "\\begin{tabular}{clcc}",
        "\\toprule",
        "\\textbf{Noise scale} & \\textbf{Policy} & \\textbf{Collision} & \\textbf{Reward} \\\\",
        "\\midrule",
        *rows,
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ])
    (out_dir / "table_noise_stress.tex").write_text(tex + "\n", encoding="utf-8")


def write_bias_table(run_dir: Path, out_dir: Path) -> None:
    shift_path = run_dir / "feature_shift.csv"
    transfer_path = run_dir / "transfer_accuracy.json"
    if not shift_path.exists():
        return
    df = pd.read_csv(shift_path)
    rows = []
    for _, row in df.iterrows():
        rows.append(
            f"{row['courtesy'].replace('_', '\\_')} & {row['feature']} & "
            f"{float(row['source_mean']):.2f} & {float(row['target_mean']):.2f} & "
            f"{float(row['standardized_mean_difference']):.2f} \\\\"
        )
    note = ""
    if transfer_path.exists():
        payload = json.loads(transfer_path.read_text(encoding="utf-8"))
        note = (
            "\\begin{tablenotes}\\small\\item "
            f"Transfer accuracy source$\\to$target: {100.0 * payload['source_to_target_acc']:.1f}\\%; "
            f"target$\\to$source: {100.0 * payload['target_to_source_acc']:.1f}\\%."
            "\\end{tablenotes}"
        )
    tex = "\n".join([
        "% Auto-generated by make_tier1_tables.py",
        "\\begin{table}[htbp]",
        "\\centering",
        "\\caption{Generating-policy feature shift between source and target datasets.}",
        "\\label{tab:generating_policy_bias}",
        "\\small",
        "\\begin{tabular}{llccc}",
        "\\toprule",
        "\\textbf{Courtesy} & \\textbf{Feature} & \\textbf{Source mean} & \\textbf{Target mean} & \\textbf{SMD} \\\\",
        "\\midrule",
        *rows,
        "\\bottomrule",
        "\\end{tabular}",
        note,
        "\\end{table}",
    ])
    (out_dir / "table_generating_policy_bias.tex").write_text(tex + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    write_confirmatory_table(Path(args.confirmatory_dir), out_dir)
    write_fullcov_table(Path(args.fullcov_dir), out_dir)
    write_noise_table(Path(args.noise_dir), out_dir)
    write_bias_table(Path(args.bias_dir), out_dir)


if __name__ == "__main__":
    main()
